<?php
/**
 * Plugin Name: EndoPlanner 2.0
 * Description: A Gutenberg‐based wizard for clinical indication, patency mapping, case summary, intervention planning, and PDF export.
 * Version:     1.6.21
 * Author:      hpebben
 * License:     GPL2+
 *
 * GitHub Plugin URI: https://github.com/hpebben/endo-planner-v2
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Load plugin translations.
 */
function endoplanner_load_textdomain() {
    load_plugin_textdomain( 'endoplanner', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
}
add_action( 'init', 'endoplanner_load_textdomain' );

/**
 * Load the asset file generated by `npm run build`.
 */
$asset_file = include( plugin_dir_path( __FILE__ ) . 'build/index.asset.php' );

/**
 * Register block JavaScript and CSS for the editor.
 */
wp_register_script(
    'endo-planner-editor-script',                       // Script handle.
    plugins_url( 'build/index.js', __FILE__ ),          // Path to built JS file.
    $asset_file['dependencies'],                        // WP-provided dependencies.
    $asset_file['version']                              // Version (auto–file‐hash).
);

wp_set_script_translations( 'endo-planner-editor-script', 'endoplanner', plugin_dir_path( __FILE__ ) . 'languages' );

wp_register_style(
    'endo-planner-editor-style',                        // Editor style handle.
    plugins_url( 'build/index.css', __FILE__ ),
    [],
    filemtime( plugin_dir_path( __FILE__ ) . 'build/index.css' )
);

wp_register_style(
    'endo-planner-frontend-style',                      // Front-end style handle.
    plugins_url( 'build/style-index.css', __FILE__ ),
    [],
    filemtime( plugin_dir_path( __FILE__ ) . 'build/style-index.css' )
);

/**
 * Now register our block via the block.json manifest.
 * We pass custom 'editor_script' and 'editor_style' handles so WP knows
 * which scripts/styles to enqueue in Gutenberg.  Likewise for front-end.
 */
register_block_type(
    __DIR__ . '/block.json',
    array(
        'editor_script' => 'endo-planner-editor-script',
        'editor_style'  => 'endo-planner-editor-style',
        'style'         => 'endo-planner-frontend-style',
    )
);

if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
    error_log( 'Plugin path = ' . plugin_dir_path( __FILE__ ) );
}
