<?php
/**
 * Plugin Name: EndoPlanner 2.0
 * Description: A Gutenberg‐based wizard for clinical indication, patency mapping, case summary, intervention planning, and PDF export.
 * Version:     1.6.1
 * Author:      hpebben
 * License:     GPL2+
 *
 * GitHub Plugin URI: https://github.com/hpebben/endo-planner-v2
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Load plugin translations.
 */
function endoplanner_load_textdomain() {
    load_plugin_textdomain( 'endoplanner', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
}
add_action( 'init', 'endoplanner_load_textdomain' );

/**
 * Load the asset file generated by `npm run build`.
 */
$asset_file = include( plugin_dir_path( __FILE__ ) . 'build/index.asset.php' );

/**
 * Register block JavaScript and CSS for the editor.
 */
wp_register_script(
    'endo-planner-block',                                // Script handle.
    plugins_url( 'build/index.js', __FILE__ ),           // Path to built JS file.
    $asset_file['dependencies'],                         // WP-provided dependencies.
    $asset_file['version']                               // Version (auto–file‐hash).
);

wp_set_script_translations( 'endo-planner-block', 'endoplanner', plugin_dir_path( __FILE__ ) . 'languages' );

wp_register_style(
    'endo-planner-editor',                               // Style handle.
    plugins_url( 'build/index.css', __FILE__ ),          // Path to built editor CSS.
    array(),                                             // No dependencies.
    filemtime( plugin_dir_path( __FILE__ ) . 'build/index.css' )
);

/**
 * Now register our block via the block.json manifest.
 * We pass custom 'editor_script' and 'editor_style' handles so WP knows
 * which scripts/styles to enqueue in Gutenberg.  Likewise for front-end.
 */
register_block_type(
    plugin_dir_path( __FILE__ ) . 'block.json',
    array(
        'editor_script' => 'endo-planner-block',
        'editor_style'  => 'endo-planner-editor',
        'script'        => 'endo-planner-block',
        'style'         => 'endo-planner-editor',
    )
);

error_log( 'Plugin path = ' . plugin_dir_path( __FILE__ ) );
