<?php
/**
 * Plugin Name: EndoPlanner 2.0
 * Description: A Gutenberg‐based wizard for clinical indication, patency mapping, case summary, intervention planning, and PDF export.
 * Version:     1.6.45
 * Author:      hpebben
 * License:     GPL2+
 *
 * GitHub Plugin URI: https://github.com/hpebben/endo-planner-v2
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Load plugin translations.
 */
function endoplanner_load_textdomain() {
    load_plugin_textdomain( 'endoplanner', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
}
add_action( 'init', 'endoplanner_load_textdomain' );

/**
 * Load the asset file generated by `npm run build`.
 */
$asset_file = include( plugin_dir_path( __FILE__ ) . 'build/index.asset.php' );

/**
 * Register block JavaScript and CSS for both the editor and the front‑end.
 */
wp_register_script(
    'endoplanner-block-js',
    plugins_url( 'build/index.js', __FILE__ ),
    $asset_file['dependencies'],
    $asset_file['version']
);

wp_set_script_translations( 'endoplanner-block-js', 'endoplanner', plugin_dir_path( __FILE__ ) . 'languages' );

wp_register_style(
    'endoplanner-editor-css',
    plugins_url( 'build/index.css', __FILE__ ),
    [],
    filemtime( plugin_dir_path( __FILE__ ) . 'build/index.css' )
);

wp_register_style(
    'endoplanner-front-css',
    plugins_url( 'build/style-index.css', __FILE__ ),
    [],
    filemtime( plugin_dir_path( __FILE__ ) . 'build/style-index.css' )
);

/**
 * Now register our block via the block.json manifest.
 * We pass custom 'editor_script' and 'editor_style' handles so WP knows
 * which scripts/styles to enqueue in Gutenberg.  Likewise for front-end.
 */
function endoplanner_render_callback( $attributes ) {
    return '<div class="endoplanner-root"></div>';
}

register_block_type(
    __DIR__ . '/block.json',
    array(
        'editor_script'   => 'endoplanner-block-js',
        'editor_style'    => 'endoplanner-editor-css',
        'script'          => 'endoplanner-block-js',
        'style'           => 'endoplanner-front-css',
        'render_callback' => 'endoplanner_render_callback',
    )
);

if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
    error_log( 'Plugin path = ' . plugin_dir_path( __FILE__ ) );
}
